- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure NTP (for time synchronization) is installed.
      yum:
        name: ntpstat.noarch
        state: present
    - name: Ensure NTP is running.
      service: 
        name: ntpd 
        state: started 
        enabled: yes
